name: Build Docker images

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions: [7, 8, 11]
    env:
      repo: "govpf/maven"
    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.5.1

    - name: Build and push
      uses: docker/build-push-action@v2.6.1
      with:
        context: .
        file: ./3/jdk-${{ matrix.versions }}/Dockerfile
        platforms: linux/amd64
        pull: true
        push: false
        tags: |
          ${{ env.repo }}:3-jdk-${{ matrix.versions }}
          ${{ env.repo }}:3.6-jdk-${{ matrix.versions }}
